//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportDetail
    {
        public int id { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> import_id { get; set; }
        public Nullable<int> warehouse_id { get; set; }
    
        public virtual Import Import { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
