//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int order_detail_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<double> product_price { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public Nullable<int> warehouse_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
