//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductImgs = new HashSet<ProductImg>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_describe { get; set; }
        public Nullable<double> product_price { get; set; }
        public Nullable<int> product_status { get; set; }
        public Nullable<int> brand_id { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string avatar_url { get; set; }
        public Nullable<int> type { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImg> ProductImgs { get; set; }
    }
}
