//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int prom_id { get; set; }
        public string prom_keycode { get; set; }
        public Nullable<int> prom_amount { get; set; }
        public Nullable<System.DateTime> prom_startdate { get; set; }
        public Nullable<System.DateTime> prom_expirationdate { get; set; }
        public Nullable<int> prom_discount { get; set; }
        public Nullable<bool> is_delete { get; set; }
    }
}
