//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int slide_id { get; set; }
        public string slide_urlfile { get; set; }
        public string slide_name { get; set; }
        public Nullable<int> slide_status { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public Nullable<int> ordernumber { get; set; }
    }
}
