//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_fullname { get; set; }
        public Nullable<System.DateTime> user_birthday { get; set; }
        public string user_phone { get; set; }
        public string user_address { get; set; }
        public string user_note { get; set; }
        public string user_email { get; set; }
        public string user_password { get; set; }
        public string user_gender { get; set; }
        public Nullable<int> user_role_id { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
